name: IQ Mart

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 Build IQ Mart Physical iPhone IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Build iOS App for Physical Hardware
        run: flutter build ios --release --no-codesign

      - name: Package Payload into .ipa
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -qq -r -9 IQ-Mart.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IQ-Mart-IPA
          path: build/ios/iphoneos/IQ-Mart.ipa
