name: IQ Mart

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 Build IQ Mart iOS Simulator App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Build iOS Simulator App
        run: flutter build ios --simulator --release

      - name: Package Simulator App (.zip)
        run: |
          cd build/ios/iphonesimulator
          zip -qq -r -9 IQ-Mart-Simulator.zip Runner.app

      - name: Upload Simulator Build
        uses: actions/upload-artifact@v4
        with:
          name: IQ-Mart-Appetize-Build
          path: build/ios/iphonesimulator/IQ-Mart-Simulator.zip
